# Generated by Django 5.2.4 on 2025-07-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_path',
            field=models.CharField(default='assets/images/bulb.png', max_length=200),
        ),
    ]
