# Generated by Django 5.2.4 on 2025-07-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_category_icon_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
