# Generated by Django 5.2.4 on 2025-09-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_resource_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('emergency', 'Emergency Procedures'), ('prevention', 'Fire Prevention'), ('equipment', 'Safety Equipment'), ('kids', 'For Kids'), ('navigation', 'Website Navigation'), ('general', 'General Information')], default='general', max_length=20)),
                ('question_text', models.CharField(max_length=200)),
                ('response_text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
    ]
